### ISSUE TITLE
Question about .gitattributes

### ISSUE THREAD

**Issue by thetayloredman** [Oxygemo/Fixdows#1]
Why is all of `.gitattributes` commented out?

**Comment by Oxygemo** [comment]
Oh. Visual Studio auto-generated .gitattributes. i don't know what that file even is, I can probably delete it.

**Comment by thetayloredman** [comment]
It basically controls what git does with some files, for example, treat `<file>.bin` as binary and convert `<file>.docx` to text before diffing etc

**Comment by Oxygemo** [comment]
Well if it doesn't even work I'll delete it.

**Comment by Oxygemo** [comment]
b14b221178129810882422515f275381bd134131

**Comment by Oxygemo** [comment]
Stale - closed.
